USER_ROLES = ["default", "moderator"]
SITE_STATUSES = ["suggested", "broken"]
CATEGORY_SITE_RELATIONSHIPS = ["tag"]
CATEGORY_SITE_STATUSES = ["suggested"]
USER_CATEGORY_RELATIONSHIPS = ["like"]
USER_SITE_RELATIONSHIPS = ["like", "dislike", "visited", "collection"]
