"""init

Revision ID: 51231287805a
Revises:
Create Date: 2025-01-05 21:00:09.633313

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "51231287805a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("parent_uuid", sa.UUID(), nullable=False),
        sa.Column("parent_name", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("name", name="category_name_key"),
    )
    op.create_index(op.f("ix_category_name"), "category", ["name"], unique=False)
    op.create_table(
        "category_group",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("name", name="category_group_name_key"),
    )
    op.create_table(
        "category_site_relationship",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("from_uuid", sa.UUID(), nullable=False),
        sa.Column("to_uuid", sa.UUID(), nullable=False),
        sa.Column("relationship", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("submitted_by", sa.UUID(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("from_uuid", "to_uuid", "relationship", name="category_site_id_key"),
    )
    op.create_index(
        op.f("ix_category_site_relationship_from_uuid"), "category_site_relationship", ["from_uuid"], unique=False
    )
    op.create_index(
        op.f("ix_category_site_relationship_to_uuid"), "category_site_relationship", ["to_uuid"], unique=False
    )
    op.create_table(
        "site",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("likes", sa.Integer(), nullable=False),
        sa.Column("dislikes", sa.Integer(), nullable=False),
        sa.Column("collections", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("thumbnail", sa.Text(), nullable=True),
        sa.Column("submitted_by", sa.UUID(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("url", name="url_key"),
    )
    op.create_table(
        "user",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("user_name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.Column("photo", sa.Text(), nullable=True),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("joined_at", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("last_login", postgresql.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("user_name", name="user_name_key"),
    )
    op.create_index(op.f("ix_user_user_name"), "user", ["user_name"], unique=False)
    op.create_table(
        "user_category_relationship",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("from_uuid", sa.UUID(), nullable=False),
        sa.Column("to_uuid", sa.UUID(), nullable=False),
        sa.Column("relationship", sa.Text(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("from_uuid", "to_uuid", "relationship", name="user_category_id_key"),
    )
    op.create_index(
        op.f("ix_user_category_relationship_from_uuid"), "user_category_relationship", ["from_uuid"], unique=False
    )
    op.create_index(
        op.f("ix_user_category_relationship_to_uuid"), "user_category_relationship", ["to_uuid"], unique=False
    )
    op.create_table(
        "user_site_relationship",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("from_uuid", sa.UUID(), nullable=False),
        sa.Column("to_uuid", sa.UUID(), nullable=False),
        sa.Column("relationship", sa.Text(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("from_uuid", "to_uuid", "relationship", name="user_site_id_key"),
    )
    op.create_index(op.f("ix_user_site_relationship_from_uuid"), "user_site_relationship", ["from_uuid"], unique=False)
    op.create_index(op.f("ix_user_site_relationship_to_uuid"), "user_site_relationship", ["to_uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_site_relationship_to_uuid"), table_name="user_site_relationship")
    op.drop_index(op.f("ix_user_site_relationship_from_uuid"), table_name="user_site_relationship")
    op.drop_table("user_site_relationship")
    op.drop_index(op.f("ix_user_category_relationship_to_uuid"), table_name="user_category_relationship")
    op.drop_index(op.f("ix_user_category_relationship_from_uuid"), table_name="user_category_relationship")
    op.drop_table("user_category_relationship")
    op.drop_index(op.f("ix_user_user_name"), table_name="user")
    op.drop_table("user")
    op.drop_table("site")
    op.drop_index(op.f("ix_category_site_relationship_to_uuid"), table_name="category_site_relationship")
    op.drop_index(op.f("ix_category_site_relationship_from_uuid"), table_name="category_site_relationship")
    op.drop_table("category_site_relationship")
    op.drop_table("category_group")
    op.drop_index(op.f("ix_category_name"), table_name="category")
    op.drop_table("category")
    # ### end Alembic commands ###
